/*
 *  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 *  This code is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License version 2 only, as
 *  published by the Free Software Foundation.  Oracle designates this
 *  particular file as subject to the "Classpath" exception as provided
 *  by Oracle in the LICENSE file that accompanied this code.
 *
 *  This code is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 *  version 2 for more details (a copy is included in the LICENSE file that
 *  accompanied this code).
 *
 *  You should have received a copy of the GNU General Public License version
 *  2 along with this work; if not, write to the Free Software Foundation,
 *  Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 *   Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 *  or visit www.oracle.com if you need additional information or have any
 *  questions.
 */

// Generated by jextract

package jdk.internal.clang.libclang;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$16 {

    static final FunctionDescriptor clang_getTokenLocation$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(2, C_POINTER).withName("ptr_data"),
        C_INT.withName("int_data"),
        MemoryLayout.paddingLayout(32)
    ),
        C_POINTER,
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(4, C_INT).withName("int_data"),
            C_POINTER.withName("ptr_data")
        )
    );
    static final MethodHandle clang_getTokenLocation$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_getTokenLocation",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemorySegment;)Ljdk/incubator/foreign/MemorySegment;",
        constants$16.clang_getTokenLocation$FUNC, false
    );
    static final FunctionDescriptor clang_getTokenExtent$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(2, C_POINTER).withName("ptr_data"),
        C_INT.withName("begin_int_data"),
        C_INT.withName("end_int_data")
    ),
        C_POINTER,
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(4, C_INT).withName("int_data"),
            C_POINTER.withName("ptr_data")
        )
    );
    static final MethodHandle clang_getTokenExtent$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_getTokenExtent",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemorySegment;)Ljdk/incubator/foreign/MemorySegment;",
        constants$16.clang_getTokenExtent$FUNC, false
    );
    static final FunctionDescriptor clang_tokenize$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(2, C_POINTER).withName("ptr_data"),
            C_INT.withName("begin_int_data"),
            C_INT.withName("end_int_data")
        ),
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle clang_tokenize$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_tokenize",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemorySegment;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$16.clang_tokenize$FUNC, false
    );
    static final FunctionDescriptor clang_disposeTokens$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle clang_disposeTokens$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_disposeTokens",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)V",
        constants$16.clang_disposeTokens$FUNC, false
    );
    static final FunctionDescriptor clang_getCursorKindSpelling$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_POINTER.withName("data"),
        C_INT.withName("private_flags"),
        MemoryLayout.paddingLayout(32)
    ),
        C_INT
    );
    static final MethodHandle clang_getCursorKindSpelling$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_getCursorKindSpelling",
        "(I)Ljdk/incubator/foreign/MemorySegment;",
        constants$16.clang_getCursorKindSpelling$FUNC, false
    );
    static final FunctionDescriptor clang_getClangVersion$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_POINTER.withName("data"),
        C_INT.withName("private_flags"),
        MemoryLayout.paddingLayout(32)
    ));
    static final MethodHandle clang_getClangVersion$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_getClangVersion",
        "()Ljdk/incubator/foreign/MemorySegment;",
        constants$16.clang_getClangVersion$FUNC, false
    );
}


