/*
 *  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 *  This code is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License version 2 only, as
 *  published by the Free Software Foundation.  Oracle designates this
 *  particular file as subject to the "Classpath" exception as provided
 *  by Oracle in the LICENSE file that accompanied this code.
 *
 *  This code is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 *  version 2 for more details (a copy is included in the LICENSE file that
 *  accompanied this code).
 *
 *  You should have received a copy of the GNU General Public License version
 *  2 along with this work; if not, write to the Free Software Foundation,
 *  Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 *   Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 *  or visit www.oracle.com if you need additional information or have any
 *  questions.
 */

// Generated by jextract

package jdk.internal.clang.libclang;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$13 {

    static final FunctionDescriptor CXCursorVisitor$FUNC = FunctionDescriptor.of(C_INT,
        MemoryLayout.structLayout(
            C_INT.withName("kind"),
            C_INT.withName("xdata"),
            MemoryLayout.sequenceLayout(3, C_POINTER).withName("data")
        ),
        MemoryLayout.structLayout(
            C_INT.withName("kind"),
            C_INT.withName("xdata"),
            MemoryLayout.sequenceLayout(3, C_POINTER).withName("data")
        ),
        C_POINTER
    );
    static final MethodHandle CXCursorVisitor$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemorySegment;Ljdk/incubator/foreign/MemorySegment;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$13.CXCursorVisitor$FUNC, false
    );
    static final FunctionDescriptor clang_visitChildren$FUNC = FunctionDescriptor.of(C_INT,
        MemoryLayout.structLayout(
            C_INT.withName("kind"),
            C_INT.withName("xdata"),
            MemoryLayout.sequenceLayout(3, C_POINTER).withName("data")
        ),
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle clang_visitChildren$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_visitChildren",
        "(Ljdk/incubator/foreign/MemorySegment;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$13.clang_visitChildren$FUNC, false
    );
    static final FunctionDescriptor clang_getCursorUSR$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_POINTER.withName("data"),
        C_INT.withName("private_flags"),
        MemoryLayout.paddingLayout(32)
    ),
        MemoryLayout.structLayout(
            C_INT.withName("kind"),
            C_INT.withName("xdata"),
            MemoryLayout.sequenceLayout(3, C_POINTER).withName("data")
        )
    );
    static final MethodHandle clang_getCursorUSR$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_getCursorUSR",
        "(Ljdk/incubator/foreign/MemorySegment;)Ljdk/incubator/foreign/MemorySegment;",
        constants$13.clang_getCursorUSR$FUNC, false
    );
    static final FunctionDescriptor clang_getCursorSpelling$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_POINTER.withName("data"),
        C_INT.withName("private_flags"),
        MemoryLayout.paddingLayout(32)
    ),
        MemoryLayout.structLayout(
            C_INT.withName("kind"),
            C_INT.withName("xdata"),
            MemoryLayout.sequenceLayout(3, C_POINTER).withName("data")
        )
    );
    static final MethodHandle clang_getCursorSpelling$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_getCursorSpelling",
        "(Ljdk/incubator/foreign/MemorySegment;)Ljdk/incubator/foreign/MemorySegment;",
        constants$13.clang_getCursorSpelling$FUNC, false
    );
    static final FunctionDescriptor clang_PrintingPolicy_getProperty$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle clang_PrintingPolicy_getProperty$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_PrintingPolicy_getProperty",
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$13.clang_PrintingPolicy_getProperty$FUNC, false
    );
    static final FunctionDescriptor clang_PrintingPolicy_setProperty$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle clang_PrintingPolicy_setProperty$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_PrintingPolicy_setProperty",
        "(Ljdk/incubator/foreign/MemoryAddress;II)V",
        constants$13.clang_PrintingPolicy_setProperty$FUNC, false
    );
}


