/*
 *  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 *  This code is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License version 2 only, as
 *  published by the Free Software Foundation.  Oracle designates this
 *  particular file as subject to the "Classpath" exception as provided
 *  by Oracle in the LICENSE file that accompanied this code.
 *
 *  This code is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 *  version 2 for more details (a copy is included in the LICENSE file that
 *  accompanied this code).
 *
 *  You should have received a copy of the GNU General Public License version
 *  2 along with this work; if not, write to the Free Software Foundation,
 *  Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 *   Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 *  or visit www.oracle.com if you need additional information or have any
 *  questions.
 */

// Generated by jextract

package jdk.internal.clang.libclang;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$3 {

    static final FunctionDescriptor clang_getNumDiagnostics$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle clang_getNumDiagnostics$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_getNumDiagnostics",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$3.clang_getNumDiagnostics$FUNC, false
    );
    static final FunctionDescriptor clang_getDiagnostic$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle clang_getDiagnostic$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_getDiagnostic",
        "(Ljdk/incubator/foreign/MemoryAddress;I)Ljdk/incubator/foreign/MemoryAddress;",
        constants$3.clang_getDiagnostic$FUNC, false
    );
    static final FunctionDescriptor clang_disposeDiagnostic$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle clang_disposeDiagnostic$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_disposeDiagnostic",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$3.clang_disposeDiagnostic$FUNC, false
    );
    static final FunctionDescriptor clang_formatDiagnostic$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_POINTER.withName("data"),
        C_INT.withName("private_flags"),
        MemoryLayout.paddingLayout(32)
    ),
        C_POINTER,
        C_INT
    );
    static final MethodHandle clang_formatDiagnostic$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_formatDiagnostic",
        "(Ljdk/incubator/foreign/MemoryAddress;I)Ljdk/incubator/foreign/MemorySegment;",
        constants$3.clang_formatDiagnostic$FUNC, false
    );
    static final FunctionDescriptor clang_defaultDiagnosticDisplayOptions$FUNC = FunctionDescriptor.of(C_INT);
    static final MethodHandle clang_defaultDiagnosticDisplayOptions$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_defaultDiagnosticDisplayOptions",
        "()I",
        constants$3.clang_defaultDiagnosticDisplayOptions$FUNC, false
    );
    static final FunctionDescriptor clang_getDiagnosticSeverity$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle clang_getDiagnosticSeverity$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_getDiagnosticSeverity",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$3.clang_getDiagnosticSeverity$FUNC, false
    );
}


