/*
 *  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 *  This code is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License version 2 only, as
 *  published by the Free Software Foundation.  Oracle designates this
 *  particular file as subject to the "Classpath" exception as provided
 *  by Oracle in the LICENSE file that accompanied this code.
 *
 *  This code is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 *  version 2 for more details (a copy is included in the LICENSE file that
 *  accompanied this code).
 *
 *  You should have received a copy of the GNU General Public License version
 *  2 along with this work; if not, write to the Free Software Foundation,
 *  Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 *   Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 *  or visit www.oracle.com if you need additional information or have any
 *  questions.
 */

// Generated by jextract

package jdk.internal.clang.libclang;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$5 {

    static final FunctionDescriptor clang_defaultReparseOptions$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle clang_defaultReparseOptions$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_defaultReparseOptions",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$5.clang_defaultReparseOptions$FUNC, false
    );
    static final FunctionDescriptor clang_reparseTranslationUnit$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle clang_reparseTranslationUnit$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_reparseTranslationUnit",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)I",
        constants$5.clang_reparseTranslationUnit$FUNC, false
    );
    static final FunctionDescriptor clang_getNullCursor$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_INT.withName("kind"),
        C_INT.withName("xdata"),
        MemoryLayout.sequenceLayout(3, C_POINTER).withName("data")
    ));
    static final MethodHandle clang_getNullCursor$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_getNullCursor",
        "()Ljdk/incubator/foreign/MemorySegment;",
        constants$5.clang_getNullCursor$FUNC, false
    );
    static final FunctionDescriptor clang_getTranslationUnitCursor$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_INT.withName("kind"),
        C_INT.withName("xdata"),
        MemoryLayout.sequenceLayout(3, C_POINTER).withName("data")
    ),
        C_POINTER
    );
    static final MethodHandle clang_getTranslationUnitCursor$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_getTranslationUnitCursor",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemorySegment;",
        constants$5.clang_getTranslationUnitCursor$FUNC, false
    );
    static final FunctionDescriptor clang_equalCursors$FUNC = FunctionDescriptor.of(C_INT,
        MemoryLayout.structLayout(
            C_INT.withName("kind"),
            C_INT.withName("xdata"),
            MemoryLayout.sequenceLayout(3, C_POINTER).withName("data")
        ),
        MemoryLayout.structLayout(
            C_INT.withName("kind"),
            C_INT.withName("xdata"),
            MemoryLayout.sequenceLayout(3, C_POINTER).withName("data")
        )
    );
    static final MethodHandle clang_equalCursors$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_equalCursors",
        "(Ljdk/incubator/foreign/MemorySegment;Ljdk/incubator/foreign/MemorySegment;)I",
        constants$5.clang_equalCursors$FUNC, false
    );
    static final FunctionDescriptor clang_Cursor_isNull$FUNC = FunctionDescriptor.of(C_INT,
        MemoryLayout.structLayout(
            C_INT.withName("kind"),
            C_INT.withName("xdata"),
            MemoryLayout.sequenceLayout(3, C_POINTER).withName("data")
        )
    );
    static final MethodHandle clang_Cursor_isNull$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_Cursor_isNull",
        "(Ljdk/incubator/foreign/MemorySegment;)I",
        constants$5.clang_Cursor_isNull$FUNC, false
    );
}


