/*
 *  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 *  This code is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License version 2 only, as
 *  published by the Free Software Foundation.  Oracle designates this
 *  particular file as subject to the "Classpath" exception as provided
 *  by Oracle in the LICENSE file that accompanied this code.
 *
 *  This code is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 *  version 2 for more details (a copy is included in the LICENSE file that
 *  accompanied this code).
 *
 *  You should have received a copy of the GNU General Public License version
 *  2 along with this work; if not, write to the Free Software Foundation,
 *  Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 *   Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 *  or visit www.oracle.com if you need additional information or have any
 *  questions.
 */

// Generated by jextract

package jdk.internal.clang.libclang;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$15 {

    static final FunctionDescriptor clang_getCursorDefinition$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_INT.withName("kind"),
        C_INT.withName("xdata"),
        MemoryLayout.sequenceLayout(3, C_POINTER).withName("data")
    ),
        MemoryLayout.structLayout(
            C_INT.withName("kind"),
            C_INT.withName("xdata"),
            MemoryLayout.sequenceLayout(3, C_POINTER).withName("data")
        )
    );
    static final MethodHandle clang_getCursorDefinition$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_getCursorDefinition",
        "(Ljdk/incubator/foreign/MemorySegment;)Ljdk/incubator/foreign/MemorySegment;",
        constants$15.clang_getCursorDefinition$FUNC, false
    );
    static final FunctionDescriptor clang_isCursorDefinition$FUNC = FunctionDescriptor.of(C_INT,
        MemoryLayout.structLayout(
            C_INT.withName("kind"),
            C_INT.withName("xdata"),
            MemoryLayout.sequenceLayout(3, C_POINTER).withName("data")
        )
    );
    static final MethodHandle clang_isCursorDefinition$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_isCursorDefinition",
        "(Ljdk/incubator/foreign/MemorySegment;)I",
        constants$15.clang_isCursorDefinition$FUNC, false
    );
    static final FunctionDescriptor clang_Cursor_isVariadic$FUNC = FunctionDescriptor.of(C_INT,
        MemoryLayout.structLayout(
            C_INT.withName("kind"),
            C_INT.withName("xdata"),
            MemoryLayout.sequenceLayout(3, C_POINTER).withName("data")
        )
    );
    static final MethodHandle clang_Cursor_isVariadic$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_Cursor_isVariadic",
        "(Ljdk/incubator/foreign/MemorySegment;)I",
        constants$15.clang_Cursor_isVariadic$FUNC, false
    );
    static final FunctionDescriptor clang_Cursor_getMangling$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_POINTER.withName("data"),
        C_INT.withName("private_flags"),
        MemoryLayout.paddingLayout(32)
    ),
        MemoryLayout.structLayout(
            C_INT.withName("kind"),
            C_INT.withName("xdata"),
            MemoryLayout.sequenceLayout(3, C_POINTER).withName("data")
        )
    );
    static final MethodHandle clang_Cursor_getMangling$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_Cursor_getMangling",
        "(Ljdk/incubator/foreign/MemorySegment;)Ljdk/incubator/foreign/MemorySegment;",
        constants$15.clang_Cursor_getMangling$FUNC, false
    );
    static final FunctionDescriptor clang_getTokenKind$FUNC = FunctionDescriptor.of(C_INT,
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(4, C_INT).withName("int_data"),
            C_POINTER.withName("ptr_data")
        )
    );
    static final MethodHandle clang_getTokenKind$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_getTokenKind",
        "(Ljdk/incubator/foreign/MemorySegment;)I",
        constants$15.clang_getTokenKind$FUNC, false
    );
    static final FunctionDescriptor clang_getTokenSpelling$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_POINTER.withName("data"),
        C_INT.withName("private_flags"),
        MemoryLayout.paddingLayout(32)
    ),
        C_POINTER,
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(4, C_INT).withName("int_data"),
            C_POINTER.withName("ptr_data")
        )
    );
    static final MethodHandle clang_getTokenSpelling$MH = RuntimeHelper.downcallHandle(
        Index_h.LIBRARIES, "clang_getTokenSpelling",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemorySegment;)Ljdk/incubator/foreign/MemorySegment;",
        constants$15.clang_getTokenSpelling$FUNC, false
    );
}


